#!/bin/bash

if [ $(basename $PWD) != "NFSIISE-CPP" ]; then
	echo "Incorrect directory"
	exit 1
fi

#Remove old directory if exists
rm -rf src || exit 1

#Create temporary directory and copy wrapper sources into it
mkdir -p src || exit 1
cp NFSIISE/src/*.c src || exit 1
cp NFSIISE/src/*.h src || exit 1
cp NFSIISE/src/Version src || exit 1
cp -r NFSIISE/src/Glide2x src || exit 1

#Patch wrapper sources
patch -p1 -i Wrapper.patch || exit 1

if [ $(uname -m) == "x86_64" ]; then
	CPU_FLAGS="-m32"
fi

if [[ $1 == "debug" ]]; then
	FLAGS="-O0 -g"
	echo "Compiling debug..."
else
	FLAGS="-Ofast -flto -s -march=native -DNDEBUG"
	echo "Compiling release..."
fi

#Compile the game
time gcc -o nfs2se -std=c++14 $CPU_FLAGS $FLAGS -DGLES2 -w src/*.c NFS2SE.cpp -lSDL2 -lGL -lm -fpermissive -fno-rtti -fno-exceptions
result=$?

#Remove temporary directory
rm -rf src

exit $result
